### ISSUE TITLE
Crowd-funding DocPad v7 (no analytics, semver plugins, javascript conversion, abstract core)

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#1055]
I keep getting tweets and messages from the loyal DocPad community, however unless there is funding, maintenance will be lacking. I've got a roadmap up on https://bevry.me/patreon - however, there isn't funding happening there, even after nearly a year of being there. So I'm thinking an official crowd-funding campaign may be the way to go.

The tasks that will complete with funding:
- [x] https://github.com/docpad/docpad/issues/1045 - update dependencies
- [x] https://github.com/docpad/docpad/issues/1041 - remove newsletter, analytics, error reporting 
- [ ] https://github.com/docpad/docpad/issues/1046 - convert from coffeescript to javascript => better tooling, larger contributor base
- [ ] https://github.com/docpad/docpad/issues/691 - semver plugins => plugins can now do breaking changes, such as updating their rendering dependency version, without breaking existing docpad installs, allowing plugin development to flourish - plugins will also be able to support multiple docpad major versions - meaning the transition to a DocPad v7 will be easy

The tasks that will be started with funding:
- [ ] https://github.com/docpad/docpad/milestone/16 - abstracted core => easier core maintenance as core will be smaller, server can now be a plugin, so plugins can target which server they want, e.g. express v4, or express v3
- [ ] https://github.com/docpad/docpad/issues/336 - track which documents reference which => super fast rendering with complicated references

Why not just do these already? These all take considerable time - months - to do. These will also be breaking changes during development, with an easy migration path, if not complete backwards compatibility afterwards - but during dev, things may break - which means a lot of testing, and a lot of infrastructure stuff. I'd also like to ensure that the work is actually going to be worth doing, rather than just making the lives of a few easier, as multiple months of work is a notable investment, that I want to make sure is going to a worthwhile investment. Doing 3 months of work unpaid, for something that may not help anyone, is not too appealing.

Considering we would want to avoid crowd-funding service fees, we would probably have to create our own / implement our own crowd-funding campaign. As this takes time, I would want to know if anyone is actually interested in implementing such a thing.

The ideal target for this batch of work will be $30,000USD - however if we can get even $10,000USD this will provide a lot of headway - or even $4,000USD will do it if I move to Asia.

If you think yourself or your company can get behind making DocPad up to date, with semver plugins, and an abstracted core, email us@bevry.me or post a comment below, with how much you think your company can sponsor.

Fund the accomplishment of this specific issue here: http://www.codefund.io/view.php?id=4

**Comment by balupton** [comment]
If the silence continues, requiring payment to use DocPad may be the way to go. I need input on this, not silence. It is very confusing to hear words of love and loyalty and requests for change yet complete silence when it is noted that their money is required for the change they request.

**Comment by aaitken** [comment]
I love it and am loyal and have observed that dev on it has slowed over time, hence my Twitter inquiry on its status. Open source / free was the initial model so yeah, switching to a money ask is a significant moment. That said, I'm in for a nominal monthly fee (or similar). Anyone else?

**Comment by balupton** [comment]
So I've got an update to make to https://github.com/bevry/joe - however work has again commenced on DocPad, starting with https://github.com/docpad/docpad/issues/1045 updating the deps to make use of all the past 2 years of innovations with the bevry deps.

At this point, until we get more people behind the notion of a crowd-funding campaign. Our patreon remains the best place to discover and fund our roadmap: https://bevry.me/patreon

**Comment by balupton** [comment]
Little status update - joe and its reporters, watchr, ignorefs have been updated for node 0.10 compatibility which was the hold up, so #1045 is ready to commence again - however before it does, it is time to actually honour the patreon rewards and develop the infrastructure needed to make that happens, so I will do that now, then get back to work on #1045

**Comment by dotmagic** [comment]
Could [decaffeinate](https://github.com/decaffeinate/decaffeinate) help us to convert some of the coffee scripts to ES6?

**Comment by balupton** [comment]
@dotmagic maybe, I've found tools like that assist the manual conversion - a lot of the time, conversions of languages require rewriting some parts for better conventions - however for the majority of code that don't require such things, tools like that help guide it

**Comment by lsdriscoll** [comment]
@balupton Hey dude, just pledged on Patreon. Not much I'm afraid because I'm just a man atm. One thing I'll say is that it took me a while of trying to find updates about the project before I found this page through your twitter, which ultimately lead me to the Patreon site. I was very close to giving up and assuming this had been abandoned. 

Have you considered a banner on the DocPad site like wikipedia did? Also, if you have enterprise users - could you tempt sponsorship with some enterprise tailored epics? I don't know if that goes against the Bevry ethos or not, just sharing ideas.

**Comment by balupton** [comment]
thanks!

followed your suggestion and added some more prominent links to the website - https://github.com/docpad/website/commit/aecce16ca25c2972bc0d896a4dbe4c8a97ec3a2e

although when you run DocPad, it also has the donation text every time, which has been there for years

for sponsorship fulfilment, discussion ongoing over at https://github.com/bevry/sponsored and https://github.com/bevry/sponsored/issues/11

glad to have you join the funding ranks!

**Comment by balupton** [comment]
okay, given this a go http://www.codefund.io/view.php?id=4

**Comment by balupton** [comment]
Seems no one cares. So giving up on funding. See #1072 for discussion.
