### ISSUE TITLE
New DocPad v6.80.0 release

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#1076]
So the first minor release in nearly two years (v6.79.0 was released on 2016 September 27).

Those years did not go unspent though, every single bevry package was updated, and this release includes all of it. See its changelog for full details.

---

Changelog: https://github.com/docpad/docpad/blob/master/HISTORY.md#v6800-2018-july-12

Documentation: http://v6.80.0.docpad.docpad.surge.sh/docs/

Install Globally: `npm install -g docpad@6.80`

Install Locally: `npm install --save docpad@6.80`

Running it with CoffeeScript v1 Plugins:

```
env EDITIONS_SYNTAX_BLACKLIST=esnext docpad run
```

Running it with all CoffeeScript v2 Plugins:

```
docpad run
```

To upgrade a plugin to CoffeeScript v2 and the latest conventions, have the plugin maintainer run [boundation](https://github.com/bevry/boundation) on their plugin repository.

---

Known issues:

- [x] [Cannot set property initialConfig of #<LessPlugin> which has only a getter](https://github.com/docpad/docpad/issues/1077) fixed in v6.80.1
- [x] [Buffer() is deprecated due to security and usability issues](https://github.com/docpad/docpad/issues/1078) fixed in v6.80.2
- [x] [Failure when scaffolding new site: extendr only supports extending plain objects](https://github.com/docpad/docpad/issues/1079) fixed in v6.80.4
- [x] [Progress bar lingers after a generation](https://github.com/docpad/docpad/issues/1080) fixed in v6.80.5

---

Use this thread for any errors related specifically to the upgrade process. Otherwise, use our [discussion forum](https://discuss.bevry.me).

v6.80 will probably be the last DocPad release. See #1072 for discussion.

Let me know what you think, or if I am just wasting my time with DocPad. Cheers!

Any help with the below error reports would be fantastic.

/cc @docpad/core-team @docpad/extras-team @docpad/meta-team

**Comment by balupton** [comment]
And the first bug. Scaffolding a new site fails.

```
> docpad run
info: Welcome to DocPad v6.80.0 (global installation: /usr/local/lib/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: https://docpad.org/donate
info: Contribute: https://docpad.org/docs/contribute
info: Plugins: 
info: Environment: development
info: Updating the exchange... 
This can take a moment...
info: Updated the exchange
info: You are about to create your new project inside your current directory. Below is a list of skeletons to bootstrap your new project:

  1.	HTML5 Boilerplate (Supported)
  	HTML5 Boilerplate skeleton for DocPad. Bare essentials for building a modern website with best practices

  2.	Casper (Supported)
  	A port of Casper, the default theme for Ghost, to DocPad

  3.	Twitter Bootstrap (Supported)
  	Simple and flexible HTML, CSS, and Javascript for popular user interface components and interactions

  4.	Twitter Bootstrap with Jade (Supported)
  	Twitter Bootstrap skeleton for DocPad developed using Jade (a HAML alternative for Node.js)

  5.	Bevry's Website (Supported)
  	Bevry's website - a simple landing page website with some custom routes

  6.	Benjamin Lupton's Website (Supported)
  	Benjamin Lupton's website - pulls in statistics, articles, videos, and projects from around the web

  7.	DocPad's Website (Supported)
  	DocPad's website - a dynamic static website that pulls in a markdown documentation repository

  8.	Bevry's Learning Centre (Supported)
  	Bevry's learning centre website - a dynamic static website that pulls in a markdown documentation repository

  9.	Static Site Generators's Website (Supported)
  	The comparison website of all the different static site generators - pulls in a yaml file that is converted to json and rendered on changes via a web hook

  10.	HTML5 Boilerplate with Jade and LESS (Unsupported)
  	A skeleton that uses the HTML5 boilerplate with Jade and LESS. Also includes jQuery and the livereload plugin

  11.	SlidePad (Unsupported)
  	Create HTML5 Presentations easily with DocPad

  12.	Slides (Unsupported)
  	A simple DocPad solution for generating smashing html slides

  13.	Reveal.js (Unsupported)
  	Create Reveal.js presentations easily with DocPad

  14.	Meny (Unsupported)
  	Create a simple page utilizing the Meny 3D menu

  15.	Conference Boilerplate (Unsupported)
  	A kickstart to create websites for conference/events

  16.	YUI PureCSS (Unsupported)
  	YUI PureCSS skeleton for DocPad by MDM

  17.	Material Design Lite Android Template (Unsupported)
  	Material Design Lite Android Template by MDM

  18.	Zurb Foundation (Unsupported)
  	A minimal Zurb Foundation skeleton with SASS and coffeescript

  19.	Casteasoft Foundation Simple Blog (Unsupported)
  	This skeleton supports blog posts, clean url, posts url using date-url based, pagination on blog posts listing, and more

  20.	No Skeleton
  	Prefer to start from scratch? You can get started without any skeleton if you wish

error: The action completed successfully
error: An error occured:

Error: extendr only supports extending plain objects, an input was not a plain object
    at custom (/usr/local/lib/node_modules/docpad/node_modules/extendr/source/index.js:14:10)
    at Object.extend (/usr/local/lib/node_modules/docpad/node_modules/extendr/source/index.js:60:9)
    at ConsoleInterface.choose (/usr/local/lib/node_modules/docpad/esnext/lib/interfaces/console.js:513:20)
    at ConsoleInterface.selectSkeletonCallback (/usr/local/lib/node_modules/docpad/esnext/lib/interfaces/console.js:434:22)
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:5665:21
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:917:16
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:3752:16
    at CSON.complete (/usr/local/lib/node_modules/docpad/node_modules/cson/esnext/index.js:34:9)
    at CSON.parseCSONString (/usr/local/lib/node_modules/docpad/node_modules/cson/esnext/index.js:412:17)
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:2125:21
    at Request.callback (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:619:12)
    at Stream.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:795:18)
    at Stream.emit (events.js:182:13)
    at Stream.EventEmitter.emit (domain.js:460:23)
    at Unzip.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/utils.js:112:12)
    at Unzip.emit (events.js:187:15)
    at Unzip.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

To report the above, follow the guide at: https://docpad.org/bug-report
Error: extendr only supports extending plain objects, an input was not a plain object
    at custom (/usr/local/lib/node_modules/docpad/node_modules/extendr/source/index.js:14:10)
    at Object.extend (/usr/local/lib/node_modules/docpad/node_modules/extendr/source/index.js:60:9)
    at ConsoleInterface.choose (/usr/local/lib/node_modules/docpad/esnext/lib/interfaces/console.js:513:20)
    at ConsoleInterface.selectSkeletonCallback (/usr/local/lib/node_modules/docpad/esnext/lib/interfaces/console.js:434:22)
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:5665:21
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:917:16
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:3752:16
    at CSON.complete (/usr/local/lib/node_modules/docpad/node_modules/cson/esnext/index.js:34:9)
    at CSON.parseCSONString (/usr/local/lib/node_modules/docpad/node_modules/cson/esnext/index.js:412:17)
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:2125:21
    at Request.callback (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:619:12)
    at Stream.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/index.js:795:18)
    at Stream.emit (events.js:182:13)
    at Stream.EventEmitter.emit (domain.js:460:23)
    at Unzip.<anonymous> (/usr/local/lib/node_modules/docpad/node_modules/superagent/lib/node/utils.js:112:12)
    at Unzip.emit (events.js:187:15)
    at Unzip.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Works fine in the test suite though. Will look into it tomorrow.

**Comment by balupton** [comment]
Also seems there is an issue with the progress bar not disappearing after a regeneration:

```
> docpad run
info: Welcome to DocPad v6.80.0 (local installation: /Users/balupton/Projects/docpad/extras/skeletons/docpad-h5bp/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: https://docpad.org/donate
info: Contribute: https://docpad.org/docs/contribute
info: Plugins: eco, livereload, marked, partials
info: Environment: development
info: LiveReload listening to new socket on channel /docpad-livereload
info: Server started on http://0.0.0.0:9778
info: In your web browser use http://127.0.0.1:9778
info: Generating...
info: Generated 16/18 files in 0.888 seconds
Performing writeFiles (postparing) at 0/1 0% --------------------------------------------------info: Watching setup starting...
Performing generate tasks ➞  Write the database cache at 1/10 10% =====---------------------------------------------info: Watching setup
info: The action completed successfully
info: Change detected at 4:57:40 pm update /Users/balupton/Projects/docpad/extras/skeletons/docpad-h5bp/src/render/index.html.eco
info: Regenerating at 4:57:40 pm
info: Generating...
info: Generated 1/18 files in 0.08 seconds
info: Regenerated at 4:57:40 pm
Performing generate tasks ➞  Write the database cache at 1/10 10% =====---------------------------------------------info: Change detected at 4:57:42 pm update /Users/balupton/Projects/docpad/extras/skeletons/docpad-h5bp/src/render/index.html.eco
info: Regenerating at 4:57:42 pm
info: Generating...
info: Generated 0/18 files in 0.006 seconds
info: Regenerated at 4:57:42 pm
Performing generate tasks ➞  generateBefore at 1/6 17% ========------------------------------------------info: Change detected at 4:57:48 pm update /Users/balupton/Projects/docpad/extras/skeletons/docpad-h5bp/src/render/index.html.eco
info: Regenerating at 4:57:48 pm
info: Generating...
info: Generated 1/18 files in 0.111 seconds
info: Regenerated at 4:57:48 pm
Performing generate tasks ➞  Write the database cache at 1/10 10% =====---------------------------------------------
```

**Comment by balupton** [comment]
Downloader plugin is busted:

```
TypeError: tar.extract is not a function
    at DestroyableTransform.<anonymous> (/Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad-plugin-downloader/esnext/downloader.plugin.js:127:44)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:460:23)
    at ClientRequest.<anonymous> (/Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/hyperquest/index.js:57:17)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:460:23)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:546:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:432:20)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:460:23)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onread (net.js:638:20)
```

**Comment by balupton** [comment]
Less plugin also has an issue:

```
warning: Failed to load the plugin: docpad-plugin-less at /Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad-plugin-less
The error follows:

TypeError: Cannot set property initialConfig of #<LessPlugin> which has only a getter
    at new BasePlugin (/Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad/esnext/lib/plugin.js:56:26)
    at new LessPlugin (/Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad-plugin-less/source/less.plugin.js:7:9)
    at PluginLoader.create (/Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad/esnext/lib/plugin-loader.js:260:26)
    at /Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad/esnext/lib/docpad.js:3595:29
    at PluginLoader.load (/Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad/esnext/lib/plugin-loader.js:240:7)
    at /Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad/esnext/lib/docpad.js:3590:27
    at PluginLoader.unsupported (/Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad/esnext/lib/plugin-loader.js:146:7)
    at /Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad/esnext/lib/docpad.js:3568:25
    at success (/Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad/esnext/lib/plugin-loader.js:71:16)
    at safefs.readFile (/Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/docpad/esnext/lib/plugin-loader.js:110:18)
    at /Users/balupton/Projects/docpad/extras/skeletons/docpad-bootstrap/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)


```

**Comment by balupton** [comment]
So all of them besides the progress bar will be straightforward. For the progressbar, I think I’ll dump it for an alternative solution that should work just as well.
