### ISSUE TITLE
Better Importer support

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#500]
To see how Importers fit into the DocPad Architecture, check out #543
## Tasks

To accomplish our army of importer support and to get the [syte skeleton](https://github.com/docpad/syte.docpad) operational we need to accomplish the following things:
- [x] easy support for creating virtual documents from existing documents
- [x] easy support for creating virtual documents from fresh
- [x] get the [tumblr plugin](http://docpad.org/p/tumblr) going
- [x] get the [syte skeleton](https://github.com/docpad/syte.docpad) going with tumblr
- [ ] get the [balupton skeleton](https://github.com/balupton/balupton.docpad) going with gists
- [x] get the [native comments plugin](http://docpad.org/p/nativecomments) going with a cleaner API

Optional tasks:
- [ ] allow plugins to take control of reading and writing files
- [ ] abstract out read and write interfaces into user land
- [ ] abstract out watch interface into user land
- [ ] allow support for bundled plugins
- [ ] better translation support
- [ ] better logging support inside file class
## Enables

[Importers like JSON, MongoDB, Dropbox, Tumblr, RSS](https://github.com/bevry/docpad/issues?labels=affects+importer&page=1&state=open)

**Comment by balupton** [comment]
This approach no longer makes sense. See here for the latest thoughts: https://discuss.bevry.me/t/docpad-architecture-vision-2015/46
